language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install

script: phpunit -c ./phpunit.xml.dist --coverage-clover build/logs/clover.xml
